version: "3.9"
services:
  worker:
    build: ./worker
    env_file: worker/.env
    depends_on:
      - mongodb
    command: python3 ./app.py
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: ffxivttvtracker
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db

volumes:
  db-data: