# fly.toml file generated for ffxivttvworker on 2022-09-04T15:44:39-04:00

app = "ffxivttvworker"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true